import { useEffect, useState } from 'react'
import { CreateAction } from '../../lib/quickCreate'
import { useToast } from '../../components/Toast'
import { useTables } from '../../lib/data'
import { customerStats, inRange, supplierStats, purchaseInDate,
} from '../../lib/metrics'
import { RangePicker, useRange } from '../../lib/range'
import { useQuickCreate } from '../../lib/quickCreate'
import { fmtCompactPeso, fmtCurrency, fmtDate, fmtLiters, fmtNum, label } from '../../lib/format'
import { ExportButton, Card, Chip, DataTable, InfoTip, PageHeader, filterCls, td } from '../../components/ui'
import CustomerDetail from './CustomerDetail'
import CustomerForm from './CustomerForm'
import { PendingBanner } from '../settings/Approvals'
import { exportTable } from '../../lib/exportXlsx'
import { receivedVolume } from '../../lib/metrics'
import type { Customer } from '../../data/types'
import SupplierDetail from './SupplierDetail'
import SupplierPriceChart from './SupplierPriceChart'
import { supplierColor } from '../../lib/chartColors'
import SupplierSharePie from './SupplierSharePie'
import QuoteForm from './QuoteForm'
import type { CustomerStat, SupplierStat } from '../../lib/metrics'

type Page = 'customers' | 'suppliers'

export default function Accounts({ page }: { page: Page }) {
  const { range } = useRange()
  const quick = useQuickCreate()
  const [search, setSearch] = useState('')
  const [detail, setDetail] = useState<CustomerStat | null>(null)
  const [supplierDetail, setSupplierDetail] = useState<SupplierStat | null>(null)
  const [quoteOpen, setQuoteOpen] = useState(false)
  const [formOpen, setFormOpen] = useState(false)
  const [editingCustomer, setEditingCustomer] = useState<Customer | null>(null)
  const toast = useToast()

  useEffect(() => {
    if (quick.consume('quote')) setQuoteOpen(true)
    if (quick.consume('account')) {
      setEditingCustomer(null)
      setFormOpen(true)
    }
  }, [quick])

  const data = useTables(['customers', 'suppliers', 'sales', 'purchases', 'supplierQuotes', 'warehouses'] as const)
  if (!data) return null
  const { customers, suppliers, sales, purchases, supplierQuotes: quotes, warehouses } = data

  // Delivered volume on both sides, per Q13 - MPower pays for what arrived, so
  // the average cost this markup is measured against has to be the same figure
  // Inventory reports.
  const received = purchases.filter((p) => p.status === 'received' && inRange(purchaseInDate(p), range))
  const buyCost = received.reduce((s, p) => s + receivedVolume(p) * p.pricePerLiter, 0)
  const buyVol = received.reduce((s, p) => s + receivedVolume(p), 0)
  const avgBuyCost = buyVol > 0 ? buyCost / buyVol : null

  const cStats = customerStats(customers, sales, range, avgBuyCost)
    .filter((s) => !search || s.customer.company.toLowerCase().includes(search.toLowerCase()))
    .sort((a, b) => b.netAmount - a.netAmount)
  const sStats = supplierStats(suppliers, purchases, quotes, range)

  /** Secondary Feature 2.12 - the account book as a spreadsheet. */
  function exportCustomers() {
    exportTable(
      `accounts-${range.from.slice(0, 10)}-to-${range.to.slice(0, 10)}`,
      'Accounts',
      [
        'Company', 'Brand', 'Lead generated by', 'Customer since', 'Payment terms (days)',
        'Office address', 'Office contact', 'Delivery address', 'Delivery contact',
        'Collection address', 'Collection contact', 'Preferred platform', 'Handle',
        'Usual price', 'Usual markup %', 'Usual payment',
        'Orders on record', 'Net volume (L)', 'Net amount',
        'Punctuality %', 'Ease of collection %', 'Avg days late', 'Open overdue', 'Overdue amount', 'Rating',
      ],
      cStats.map(({ customer: c, ...st }) => [
        c.company, c.brand ?? '', c.leadGeneratedBy ?? '',
        c.customerSince ? c.customerSince.slice(0, 10) : '',
        c.paymentTermDays,
        c.office?.address ?? c.address, c.office?.contactPerson ?? c.contactPerson,
        c.delivery?.address ?? '', c.delivery?.contactPerson ?? '',
        c.collection?.address ?? c.collectionAddress ?? '', c.collection?.contactPerson ?? '',
        c.preferredContact?.platform ? label(c.preferredContact.platform) : '',
        c.preferredContact?.handle ?? '',
        c.usualPricePerLiter ?? null, c.usualMarkupPct ?? null,
        c.usualPaymentMode ? label(c.usualPaymentMode) : '',
        st.orderCount, st.netVolume, st.netAmount,
        st.history.punctuality === null ? null : Math.round(st.history.punctuality * 100),
        st.history.ease === null ? null : Math.round(st.history.ease * 100),
        st.history.avgDaysLate,
        st.history.openOverdue, st.history.overdueAmount,
        st.rating ? label(st.rating) : '',
      ]),
    )
  }


  return (
    <>
      {/* Secondary Feature 2.1 - staff see their own parked inputs where they work. */}
      <PendingBanner tbl="customers" />
      <PageHeader
        title={page === 'customers' ? 'Customer accounts' : 'Supplier accounts'}
        right={
          <span className="flex items-center gap-2">
            <RangePicker />
            {page === 'customers' && <ExportButton onClick={exportCustomers} />}
            <CreateAction />
          </span>
        }
      />

      {page === 'customers' && (
        <Card delay={50}>
          <div className="flex items-center gap-[10px] border-b border-linesoft px-[14px] py-[10px]">
            <span className="text-[13px] font-semibold">Accounts</span>
            <span className="font-meta text-[12px] text-mut">{cStats.length}</span>
            <InfoTip label="What a row opens">
              Opening a row shows the account’s credit history, its office, delivery and collection
              contacts, and which opening documents are on file.
            </InfoTip>
            <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Filter by company…" className={`ml-auto w-[200px] ${filterCls}`} />
          </div>
          <DataTable
            pageSize={10}
            resetKey={`${search}|${range.from}|${range.to}`}
            cols={[
              { label: 'Customer' }, { label: 'Years' }, { label: 'Avg order', align: 'right' },
              { label: 'Reorders' }, { label: 'Usual price', align: 'right' }, { label: 'Payment' },
              { label: 'Credit' }, { label: 'Net this period', align: 'right' },
            ]}
          >
            {cStats.map((s) => (
              <tr key={s.customer.id} onClick={() => setDetail(s)} className="cursor-pointer hover:bg-hovrow">
                <td className={`${td} pl-[14px]`}>
                  <p className="m-0 font-semibold">{s.customer.company}</p>
                  <p className="m-0 text-[12px] text-faint">{s.customer.address}</p>
                </td>
                <td className={`${td} whitespace-nowrap text-mut`}>{s.yearsWith !== null ? `${Math.max(Math.round(s.yearsWith), 1)} yr${Math.round(s.yearsWith) > 1 ? 's' : ''}` : '—'}</td>
                <td className={`${td} whitespace-nowrap text-right font-semibold`}>{fmtLiters(Math.round(s.avgOrderLiters))}</td>
                <td className={`${td} whitespace-nowrap text-mut`}>{s.reorderDays !== null ? `every ${s.reorderDays} days` : '—'}</td>
                <td className={`${td} whitespace-nowrap text-right`}>
                  {s.avgPrice > 0 ? `₱${s.avgPrice.toFixed(2)}/L` : '—'}
                  {s.markup !== null && <span className="text-faint"> (+₱{s.markup.toFixed(1)})</span>}
                </td>
                <td className={`${td} whitespace-nowrap text-mut`}>{s.usualPayment ? label(s.usualPayment) : '—'}</td>
                <td className={`${td} whitespace-nowrap`}>
                  {s.rating
                    ? <Chip status={s.rating} text={s.rating === 'poor' && s.overdueAmount > 0 ? `Poor · ${fmtCompactPeso(s.overdueAmount)} overdue` : label(s.rating)} />
                    : <span className="text-faint">No history</span>}
                </td>
                <td className={`${td} whitespace-nowrap pr-[14px] text-right font-semibold`}>
                  {s.netVolume > 0 ? `${fmtNum(s.netVolume)} L · ${fmtCompactPeso(s.netAmount)}` : '—'}
                </td>
              </tr>
            ))}
          </DataTable>
        </Card>
      )}

      {page === 'suppliers' && (
        <>
          <div className="mb-[18px] grid grid-cols-[360px_1fr] items-stretch gap-[18px]">
            <SupplierSharePie stats={sStats} suppliers={suppliers} />
            <SupplierPriceChart suppliers={suppliers} quotes={quotes} purchases={purchases} />
          </div>

          <Card delay={150}>
            <div className="flex items-center gap-[10px] border-b border-linesoft px-[14px] py-[10px]">
              <span className="text-[13px] font-semibold">Suppliers</span>
              <span className="font-meta text-[12px] text-mut">{sStats.length}</span>
              <InfoTip label="What these columns compare">
                Quoted against paid, over the selected period, so a supplier who quotes well and
                invoices differently shows up. Opening a row gives its quote and purchase history.
              </InfoTip>
            </div>
            <DataTable
              pageSize={10}
              resetKey={`${range.from}|${range.to}`}
              cols={[
                { label: 'Supplier' }, { label: 'Purchases', align: 'right' }, { label: 'Volume', align: 'right' },
                { label: 'Spend', align: 'right' }, { label: 'Avg quoted', align: 'right' },
                { label: 'Avg paid', align: 'right' }, { label: 'Last quote', align: 'right' },
              ]}
            >
              {sStats.map((s) => (
                <tr key={s.supplier.id} onClick={() => setSupplierDetail(s)} className="cursor-pointer hover:bg-hovrow">
                  <td className={`${td} pl-[14px]`}>
                    <p className="m-0 flex items-center gap-2 font-semibold">
                      <span className="h-[9px] w-[9px] rounded-full" style={{ background: supplierColor(s.supplier.id, suppliers) }} />
                      {s.supplier.name}
                    </p>
                    <p className="m-0 pl-[17px] text-[12px] text-faint">{s.supplier.contactPerson} · {s.supplier.contactNumber}</p>
                  </td>
                  <td className={`${td} whitespace-nowrap text-right text-mut`}>{s.purchaseCount}</td>
                  <td className={`${td} whitespace-nowrap text-right font-semibold`}>{fmtLiters(s.totalVolume)}</td>
                  <td className={`${td} whitespace-nowrap text-right font-semibold`}>{fmtCurrency(s.totalSpend).replace('.00', '')}</td>
                  <td className={`${td} whitespace-nowrap text-right text-mut`}>{s.avgQuoted !== null ? `₱${s.avgQuoted.toFixed(2)}/L` : '—'}</td>
                  <td className={`${td} whitespace-nowrap text-right`}>
                    {s.avgPaid !== null ? (
                      <span className={s.avgQuoted !== null && s.avgPaid < s.avgQuoted ? 'font-semibold text-tealtext' : 'font-semibold'}>
                        ₱{s.avgPaid.toFixed(2)}/L
                      </span>
                    ) : '—'}
                  </td>
                  <td className={`${td} whitespace-nowrap pr-[14px] text-right text-mut`}>
                    {s.lastQuote ? `₱${s.lastQuote.pricePerLiter.toFixed(2)} · ${fmtDate(s.lastQuote.date).replace(', 2026', '')}` : '—'}
                  </td>
                </tr>
              ))}
            </DataTable>
          </Card>
        </>
      )}

      <CustomerDetail
        stat={detail}
        sales={sales}
        inRangeFn={(d) => inRange(d, range)}
        onClose={() => setDetail(null)}
        onEdit={() => {
          if (!detail) return
          setEditingCustomer(detail.customer)
          setDetail(null)
          setFormOpen(true)
        }}
      />

      <CustomerForm
        open={formOpen}
        editing={editingCustomer}
        onClose={() => { setFormOpen(false); setEditingCustomer(null) }}
        onNotice={toast}
      />
      <SupplierDetail
        stat={supplierDetail} purchases={purchases} quotes={quotes} warehouses={warehouses}
        onClose={() => setSupplierDetail(null)}
      />
      <QuoteForm open={quoteOpen} suppliers={suppliers} onClose={() => setQuoteOpen(false)} />
    </>
  )
}
