// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, render, screen } from '@testing-library/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import CustomerDetail from './CustomerDetail'
import type { CustomerStat } from '../../lib/metrics'
import type { Customer } from '../../data/types'

afterEach(cleanup)

vi.mock('../../lib/attachments', async (original) => ({
  ...(await original<typeof import('../../lib/attachments')>()),
  useAttachments: () => ({ data: [{ slot: 'bir2303' }, { slot: 'businessPermit' }] }),
}))

const customer = {
  id: 'c1',
  createdAt: '2022-03-02T00:00:00.000Z',
  updatedAt: '2022-03-02T00:00:00.000Z',
  company: 'Nova Fuels Inc.',
  brand: 'Petron',
  address: 'Km 21 MacArthur Hwy, Valenzuela',
  contactPerson: 'R. Cruz',
  contactNumber: '0917 555 0148',
  paymentTermDays: 30,
} as Customer

const stat = (over: Partial<CustomerStat> = {}): CustomerStat => ({
  customer,
  orderCount: 23,
  avgOrderLiters: 17400,
  reorderDays: 18,
  avgPrice: 56.4,
  markup: 2.35,
  usualPayment: 'check',
  yearsWith: 4,
  rating: 'good',
  overdueCount: 0,
  overdueAmount: 0,
  history: { punctuality: 0.92, ease: 0.78, avgDaysLate: 4, settled: 61, bounced: 2 },
  ...over,
} as CustomerStat)

const view = (s: CustomerStat) => render(
  <QueryClientProvider client={new QueryClient()}>
    <CustomerDetail stat={s} sales={[]} onClose={() => {}} />
  </QueryClientProvider>,
)

describe('CustomerDetail', () => {
  /** The two questions an account is opened to answer - are they good for it,
   *  do they owe us anything now - used to be the fifth and sixth blocks down a
   *  scroll, in the same type as the lead source. */
  it('puts credit standing and what is owed in the rail', () => {
    view(stat({ overdueCount: 2, overdueAmount: 480_000 }))
    expect(screen.getByText('Credit standing')).toBeTruthy()
    expect(screen.getByText('Punctuality of payment')).toBeTruthy()
    expect(screen.getByText('Overdue installments')).toBeTruthy()
  })

  it('says so plainly when nothing is overdue', () => {
    view(stat())
    expect(screen.getByText('Nothing overdue.')).toBeTruthy()
    expect(screen.queryByText('Overdue installments')).toBeNull()
  })

  it('counts the account opening documents on file', () => {
    view(stat())
    expect(screen.getByText('2 of 4')).toBeTruthy()
    expect(screen.getByText(/Still to file/)).toBeTruthy()
  })

  /** An unset field says it is unset. Hiding it made the dialog quietly shorten
   *  itself, so you could not tell whether the System had no field for a lead
   *  source or simply no value in it. */
  it('marks unrecorded fields rather than dropping them', () => {
    view(stat())
    expect(screen.getByText('Lead generated by')).toBeTruthy()
    expect(screen.getAllByText('Not recorded').length).toBeGreaterThan(0)
  })
})
